spring:
  application:
    name: chat
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chat_room?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  # session
  session:
    store-type: redis
  # redis
  data:
    redis:
      port: 6379
      host: 127.0.0.1
      database: 0

server:
  port: 8080
  servlet:
    context-path: /api
#logging:
#  level:
#    org:
#      springframework:
#        cache: DEBUG
#        session: DEBUG

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: icu.yeguo.chat.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

picgo:
  path:
    windows: E:\\Opt\\npm_package\\picgo.cmd
    linux: /root/.nvm/versions/node/v22.6.0/bin/picgo
